# Generated by Django 3.1.7 on 2021-04-20 19:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=50, verbose_name='Heading')),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='images/test-photo.jpg', null=True, upload_to='images/', verbose_name='Icon')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.DeleteModel(
            name='ArtciclesModel',
        ),
    ]
